openapi: 3.1.0
info:
  title: CityBikes API Documentation
  description: |-
    This is document explains how to use the CityBikes API.  

    CityBikes, powered by [PyBikes](https://github.com/eskerda/pybikes),  is an open-source project providing information about global  bike-sharing transportation services.  

    **Note:** This documentation is for educational purposes, aimed at using Redoc to improve the [existing documentation](https://api.citybik.es/v2/).
tags:
  - name: Authentication
    description: No authentication or API key required.
  - name: Base URL
    description: The base URL for the API is `http://api.citybik.es/v2`
  - name: Networks
    description: |-
      A network is a collection of bikes available for a short-term rental.   

      Data for a network includes information about the networks, their  names, IDs, stations, available bikes, and locations.
paths:
  /networks:
    get:
      summary: GET /networks
      description: 'This endpoint provides data about all available bike networks  around the world, including their names and IDs. '
      tags:
        - Networks
      parameters:
        - in: query
          name: id
          required: false
          schema:
            type: string
          description: Filters out the bike network ID
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Filters out the bike network name
        - in: query
          name: href
          required: false
          schema:
            type: string
          description: Filters out the bike network's API endpoint
      responses:
        '200':
          description: A list of bike networks.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BikeNetworks'
components:
  schemas:
    BikeNetworks:
      description: Information about avaliable global bike networks.
      type: object
      properties:
        networks:
          type: array
          description: Bike networks.
          items:
            $ref: '#/components/schemas/BikeNetwork'
    BikeNetwork:
      description: Information about a singular bike network.
      type: object
      properties:
        company:
          type: list
          description: List of companies involved with the bike network.
          items:
            type: string
        href:
          type: string
          description: The network's API endpoint.
        id:
          type: string
          description: The ID of the bike network.
        location:
          type: object
          description: Location of the bike network.
          $ref: '#/components/schemas/Location'
        name:
          type: string
          description: The name of the bike network.
      example:
        company:
          - Cyclopolis Systems
        href: /v2/networks/cyclopolis-maroussi
        id: cyclopolis-maroussi
        location:
          city: Maroussi
          country: GR
          latitude: 38.0568722388
          longitude: 23.8083299536
        name: Cyclopolis
    Location:
      description: The location of a bike network.
      type: object
      properties:
        city:
          type: string
          description: The name of the city.
        country:
          type: string
          description: The country code/abbreviation.
        latitude:
          type: number
          description: The latitude coordinate.
        longitude:
          type: number
          description: The longitude coordinate.
