openapi: 3.1.0
info:
  title: CityBikes API Documentation
  description: |
    # Introduction
    This is document explains how to use the CityBikes API.  

    CityBikes, powered by [PyBikes](https://github.com/eskerda/pybikes),  is an open-source project providing information about global  bike-sharing transportation services.  

    **Note:** This documentation is for educational purposes, aimed to use  Redoc to improve the existing documentation  [located here](https://api.citybik.es/v2/).  
tags:
  - name: Authentication
    description: No authentication or API key required.
  - name: Base URL
    description: The base URL for the API is `http://api.citybik.es/v2`
  - name: Networks
    description: A network is a collection of bikes available for a short-term rental.  Data for a network includes information about the networks, their  names, IDs, stations, available bikes, and locations.
paths:
  /networks:
    get:
      summary: GET /networks
      description: 'Data about all available bike networks around the world, including  their names and IDs. '
      tags:
        - Networks
      responses:
        '200':
          description: A list of networks.
          content:
            application/json:
              schema:
                type: list
components: {}
