openapi: 3.1.0
info:
  title: CityBikes API Documentation
  description: >-
    This is document explains how to use the CityBikes API.  


    CityBikes, powered by [PyBikes](https://github.com/eskerda/pybikes), 
    is an open-source project providing information about global 
    bike-sharing transportation services.  


    **Note:** This documentation is for educational purposes, aimed at using
    Redoc to improve the [existing documentation](https://api.citybik.es/v2/).
paths:
  /networks:
    get:
      summary: GET /networks
      description: >-
        This endpoint provides data about all available bike networks, 
        including their names, IDs, locations, and associated companies.
      tags:
        - Networks
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
            enum:
              - id
              - name
              - company
              - location
              - href
          description: Fields to filter for; results will render only filtered values.
      responses:
        '200':
          description: A list of bike networks.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BikeNetworks'
  /networks/{network_id}:
    get:
      summary: GET /networks/{network_id}
      description: >-
        This endpoint provides data about a specific bike network, including 
        all the available stations and bikes.
      tags:
        - Networks
      parameters:
        - name: network_id
          in: path
          required: true
          description: The ID of the bike network.
          example: xian-public-bicycle
        - name: fields
          in: query
          required: false
          schema:
            type: string
            enum:
              - id
              - name
              - company
              - location
              - href
          description: Fields to filter for; results will render only filtered values.
      responses:
        '200':
          description: Detailed information about a bike network.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BikeNetwork'
components:
  schemas:
    BikeNetwork:
      description: Information about a bike network.
      type: object
      properties:
        network:
          type: array
          description: Information about the network's location, name, ID, and stations.
          items:
            $ref: '#/components/schemas/BikeNetworkDetailed'
    BikeNetworks:
      description: Information about avaliable global bike networks.
      type: object
      properties:
        networks:
          type: array
          description: Bike networks.
          items:
            $ref: '#/components/schemas/BikeNetworkSummary'
    BikeNetworkDetailed:
      description: Detailed information about a singular bike network.
      type: object
      properties:
        company:
          type: list
          description: List of companies involved with the bike network.
          items:
            type: string
        href: 
          type: string
          description: The network's API endpoint.
        id:
          type: string
          description: The ID of the bike network.
        location:
          type: object
          description: Location of the bike network.
          $ref: '#/components/schemas/Location'
        name:
          type: string
          description: The name of the bike network.
        stations:
          description: List of all the network's bike stations.
          type: array
          items:
            $ref: '#/components/schemas/Station'
    BikeNetworkSummary:
      description: Summarized information about a singular bike network.
      type: object
      properties:
        company:
          type: list
          description: List of companies involved with the bike network.
          items:
            type: string
        href: 
          type: string
          description: The network's API endpoint.
        id:
          type: string
          description: The ID of the bike network.
        location:
          type: object
          description: Location of the bike network.
          $ref: '#/components/schemas/Location'
        name:
          type: string
          description: The name of the bike network.
      example:
        company: [Cyclopolis Systems]
        href: /v2/networks/cyclopolis-maroussi
        id: cyclopolis-maroussi
        location:
          city: Maroussi
          country: GR
          latitude: 38.0568722388
          longitude: 23.8083299536
        name: Cyclopolis
    Location:
      description: The location of a bike network.
      type: object
      properties:
        city:
          type: string
          description: The name of the city.
          example: Miami, FL
        country:
          type: string
          description: The country code/abbreviation.
          example: US
        latitude:
          type: number
          description: The latitude coordinate.
          example: 25.790654
        longitude:
          type: number
          description: The longitude coordinate.
          example: -80.1300455
    Station:
      description: A dock from which a bike can be rented and returned to. 
      type: object
      properties:
        empty_slots:
          type: integer
          description: The number of empty spaces avaliable in the bike station.
          example: 7
        extra:
          type: object
          properties:
            slots:
              type: integer
              description: The total number of bike slots in the station.
              example: 11
            uid:
              type: integer
              description: The unique identifier of the station.
              example: 3001
        free_bikes:
          type: integer
          description: The number of bikes avaliable at the bike station.
          example: 5
        id:
          type: string
          description: The unique ID of the bike station.
          example: 81cd2f7eb1e66820021e319b59196e52
        latitude:
          type: number
          description: The latitude coordinate of the bike station.
          example: 52.668746
        longitude:
          type: number
          description: The longitude coordinate of the bike station.
          example: -8.627809
        name:
          type: string
          description: The name of the bike station.
          example: Saint Mary's Cathedral
        timestamp:
          type: string
          description: Timestamp of the last time station info was updated in the system.
          example: "2024-03-04T18:14:34.202000Z"




        




tags:
  - name: Authentication 
    description: No authentication or API key required. 
  - name: Base URL
    description: The base URL for the API is `http://api.citybik.es/v2`
  - name: Networks
    description: >-
      A network is a collection of bikes available for a short-term rental.   
      

      Data for a network includes information about the networks, their 
      names, IDs, stations, available bikes, and locations.