openapi: 3.1.0
info:
  title: CityBikes API Documentation
  description: >-
    This is document explains how to use the CityBikes API.  


    CityBikes, powered by [PyBikes](https://github.com/eskerda/pybikes), 
    is an open-source project providing information about global 
    bike-sharing transportation services.  


    This document aims to leverage Redoc to enhance 
    the [existing documentation](https://api.citybik.es/v2/).


    *Last updated: March 9, 2024*

    # Authentication  
    
    No authentication or API key required. 

    # Base URL  

    The base URL for the API is `http://api.citybik.es/v2`

  x-logo:
    #url: 'https://camo.githubusercontent.com/3cab180da3ff41b6d1cfc114109cff8ff10a4d13d6e218e5a616109bfe6cd93d/687474703a2f2f6369747962696b2e65732f66696c65732f707962696b65732e706e67'
    url: 'https://eskerda.com/wp-content/uploads/2014/05/citybikes-logo.png'
    altText: PyBikes Logo
paths:
  /networks:
    get:
      summary: Get all bike networks
      description: >-
        This endpoint provides data about all available bike networks, 
        including their names, IDs, locations, and associated companies.
      tags:
        - Networks
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
            enum:
              - id
              - name
              - company
              - location
              - href
          description: Fields to filter for; results will render only filtered values.
      responses:
        '200':
          description: A list of bike networks.
          content:
            application/json:
              schema:
                type: object
                properties:
                  networks:
                    type: array
                    description: Bike networks.
                    items:
                      $ref: '#/components/schemas/BikeNetworkSummary'
  /networks/{network_id}:
    get:
      summary: GET data about a specific bike network
      description: >-
        This endpoint provides data about a specific bike network, including 
        all the available stations and bikes.  


        A **station** is a dock from which a bike can be rented and returned to. 
      tags:
        - Networks
      parameters:
        - name: network_id
          in: path
          required: true
          description: The ID of the bike network.
          example: xian-public-bicycle
        - name: fields
          in: query
          required: false
          schema:
            type: string
            enum:
              - id
              - name
              - company
              - location
              - href
              - stations
          description: Fields to filter for; results will render only filtered values.
      responses:
        '200':
          description: Detailed information about a bike network.
          content:
            application/json:
              schema:
                type: object
                properties:
                  network:
                    type: array
                    description: Information about the network's location, name, ID, and stations.
                    items:
                      $ref: '#/components/schemas/BikeNetworkDetailed'
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: Not Found
                status: 404
components:
  schemas:
    BikeNetworks:
      description: Information about avaliable global bike networks.
      type: object
      properties:
        networks:
          type: array
          description: Bike networks.
          items:
            $ref: '#/components/schemas/BikeNetworkSummary'
    BikeNetworkDetailed:
      description: Detailed information about a singular bike network.
      type: object
      properties:
        company:
          type: list
          description: List of companies involved with the bike network.
          items:
            type: string
          example: [DecoBike LLC]
        href: 
          type: string
          description: The network's API endpoint.
          example: /v2/networks/citi-bike-miami
        id:
          type: string
          description: The ID of the bike network.
          example: citi-bike-miami
        location:
          type: object
          description: Location of the bike network.
          $ref: '#/components/schemas/Location'
        name:
          type: string
          description: The name of the bike network.
          example: Citi Bike Miami
        stations:
          description: List of all the network's bike stations.
          type: array
          items:
            $ref: '#/components/schemas/Station'
    BikeNetworkSummary:
      description: Summarized information about a singular bike network.
      type: object
      properties:
        company:
          type: list
          description: List of companies involved with the bike network.
          items:
            type: string
        href: 
          type: string
          description: The network's API endpoint.
        id:
          type: string
          description: The ID of the bike network.
        location:
          type: object
          description: Location of the bike network.
          $ref: '#/components/schemas/Location'
        name:
          type: string
          description: The name of the bike network.
      example:
        company: [Cyclopolis Systems]
        href: /v2/networks/cyclopolis-maroussi
        id: cyclopolis-maroussi
        location:
          city: Maroussi
          country: GR
          latitude: 38.0568722388
          longitude: 23.8083299536
        name: Cyclopolis
    Location:
      description: The location of a bike network.
      type: object
      properties:
        city:
          type: string
          description: The name of the city.
          example: Miami, FL
        country:
          type: string
          description: The country code/abbreviation.
          example: US
        latitude:
          type: number
          description: The latitude coordinate.
          example: 25.790654
        longitude:
          type: number
          description: The longitude coordinate.
          example: -80.1300455
    Station:
      description: A dock from which a bike can be rented and returned to. 
      type: object
      properties:
        empty_slots:
          type: integer
          description: The number of empty spaces avaliable in the bike station.
          example: 9
        extra:
          type: object
          $ref: '#/components/schemas/ExtraStationInfo'
        free_bikes:
          type: integer
          description: The number of bikes avaliable at the bike station.
          example: 7
        id:
          type: string
          description: The unique ID of the bike station.
          example: 50c12c755c09aad1e465827f3c19ea1c
        latitude:
          type: number
          description: The latitude coordinate of the bike station.
          example: 25.729275
        longitude:
          type: number
          description: The longitude coordinate of the bike station.
          example: -80.241581
        name:
          type: string
          description: The name of the bike station.
          example: 000605 - Virginia St & Florida Ave
        timestamp:
          type: string
          description: Timestamp of the last time station info was updated in the system.
          example: "2024-03-05T18:30:58.668000Z"
    ExtraStationInfo:
      description: Extra information about a bike station.
      type: object
      properties:
        slots:
          type: integer
          required: false
          description: The total number of bike slots in the station.
          example: 11
        uid:
          type: [integer, string]
          description: The unique identifier of the station.
          required: false
          example: "000605"
        address:
          type: string
          description: Address location of the bike station.
          required: false
          example: "Virginia St & Florida Ave"
        online:
          type: boolean
          description: Whether or not the bikes are online.
          required: false
          example: true
        normal_bikes:
          type: integer
          required: false
          description: The number of regular bikes at the station.
          example: 5
        e_bikes:
          type: integer
          required: false
          description: The number of e-bikes at the station.
          example: 0
tags:
  - name: Networks
    description: >-
      A network is a collection of bikes available for a short-term rental.   
      

      Data for a network includes information about the networks, their 
      names, IDs, stations, available bikes, and locations.
